# Generated by Django 4.0.6 on 2024-03-18 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='artigos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('corpoDoArtigo', models.CharField(max_length=1000)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='')),
                ('horaPublicacao', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='autores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiroNome', models.CharField(max_length=100)),
                ('ultimoNome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('fotoPerfil', models.ImageField(blank=True, null=True, upload_to='')),
                ('idade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='comentarioRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=1000)),
                ('rating', models.IntegerField()),
                ('horaComentario', models.DateTimeField()),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentariosRatings', to='BlogApp.artigos')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentariosRatings', to='BlogApp.autores')),
            ],
        ),
        migrations.AddField(
            model_name='artigos',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artigos', to='BlogApp.autores'),
        ),
    ]
