# Generated by Django 4.0.6 on 2024-04-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='app/fotos'),
        ),
        migrations.AlterField(
            model_name='autores',
            name='fotoPerfil',
            field=models.ImageField(blank=True, null=True, upload_to='app/fotos'),
        ),
    ]
