# Generated by Django 4.0.6 on 2024-05-29 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BlogApp', '0002_alter_artigos_imagem_alter_autores_fotoperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigos',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artigos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comentariorating',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentariosRatings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='autores',
        ),
    ]
