# Generated by Django 4.0.6 on 2024-05-30 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0005_artigos_categoria_artigos_introducao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigos',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='artigos',
            name='introducao',
        ),
    ]
