# Generated by Django 4.0.6 on 2024-04-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='banda',
            field=models.ManyToManyField(related_name='Festivais', to='festivais.banda'),
        ),
    ]
