# Generated by Django 4.0.6 on 2024-04-05 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCientifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('semestre', models.CharField(max_length=50)),
                ('ects', models.IntegerField()),
                ('curricularUnitReadableCode', models.CharField(max_length=50)),
                ('areaCientifica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Disciplina', to='curso.areacientifica')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LinguagemProgramacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('conceitosAplicados', models.TextField()),
                ('tecnologiasUtilizadas', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='')),
                ('linkYoutube', models.URLField()),
                ('linkGitHub', models.URLField()),
                ('disciplina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Projeto', to='curso.disciplina')),
                ('linguagensProgramacao', models.ManyToManyField(related_name='Projetos', to='curso.linguagemprogramacao')),
            ],
        ),
        migrations.AddField(
            model_name='disciplina',
            name='docentes',
            field=models.ManyToManyField(blank=True, null=True, related_name='Disciplinas', to='curso.docente'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='linguagensProgramacao',
            field=models.ManyToManyField(blank=True, null=True, related_name='Disciplinas', to='curso.linguagemprogramacao'),
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('apresentacao', models.TextField()),
                ('objectivos', models.TextField()),
                ('competencias', models.TextField()),
                ('condicoesAcesso', models.TextField()),
                ('oportunidadesCarreira', models.TextField()),
                ('departamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Curso', to='curso.departamento')),
            ],
        ),
    ]
