# Generated by Django 4.0.6 on 2024-04-07 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='areaCientifica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Disciplina', to='curso.areacientifica'),
        ),
    ]
