# Generated by Django 4.0.6 on 2024-05-23 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_alter_disciplina_areacientifica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Curso', to='curso.departamento'),
        ),
    ]
