# Generated by Django 4.0.6 on 2024-05-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_alter_curso_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='disciplinas',
            field=models.ManyToManyField(related_name='Curso', to='curso.disciplina'),
        ),
    ]
