# Generated by Django 4.0.6 on 2024-06-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_curso_disciplinas'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='app/fotos'),
        ),
    ]
