# Generated by Django 4.0.6 on 2024-04-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='anoLancamento',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
