# Generated by Django 4.0.6 on 2024-04-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_album_anolancamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='cover',
        ),
        migrations.AddField(
            model_name='music',
            name='durarion',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
