# Generated by Django 4.0.6 on 2024-04-02 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0003_remove_album_cover_music_durarion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='durarion',
            new_name='duration',
        ),
    ]
