# Generated by Django 4.0.6 on 2024-05-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0005_alter_album_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='biografia',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AddField(
            model_name='band',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='app/fotos'),
        ),
        migrations.AddField(
            model_name='music',
            name='letra',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
    ]
