# Generated by Django 4.0.6 on 2024-05-29 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0007_album_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='imagem',
            new_name='imagemAlbum',
        ),
    ]
